import o from 'osyd'

import { Shell } from '../components/shell'
import type { OC } from '../types/appState'

export const MethodsPage: OC = {
  view: () =>
    o(Shell,
      { page: 'methods', wk: 'Methods & receipts', footer: vfFooter() },

      o('h2', 'The stat'),
      o('p',
        'PSR starts from the simplest thing a scoreboard can tell you: a team’s ',
        o('b', 'share of the points scored in its games'),
        ', on a 0–100 scale where 50 is league average. Every rating on the front page decomposes exactly into the layers below — point share, schedule, recency, reversion — and the pieces sum to the number shown.',
      ),

      o('h2', 'The layers'),
      o('p',
        o('b', '1 · Smoothing.'),
        ' Raw point share is unstable in shutouts and low-scoring blowouts, so each game is scored as ',
        o('code', '(PF + k) / (PF + PA + 2k) × 100'),
        ' with ',
        o('code', 'k = 14'),
        ' phantom points per side. A 3–0 win reads as a narrow edge, not perfection.',
      ),
      o('p',
        o('b', '2 · Schedule.'),
        ' An SRS-style iterative opponent adjustment: ',
        o('code', 'AdjPSR = GamePSR + (OppRating − 50)'),
        ', iterated until ratings and adjustments agree. Beating good teams counts for more.',
      ),
      o('p',
        o('b', '3 · Recency.'),
        ' Games are weighted ',
        o('code', '0.5 ^ (games_back / 12)'),
        ' — a twelve-game half-life. Recent form matters more than September, but no game ever fully ages out within a season.',
      ),
      o('p',
        o('b', '4 · Reversion.'),
        ' Ratings are shrunk toward a prior of 8 phantom games at a target of 50 plus 30% of the team’s prior-season deviation. Early on this keeps small samples sane; even late in the season it retains real weight, because extreme results are always part skill, part fortune — and pulling hot teams back toward average is, empirically, what predicts best.',
      ),
      o('p',
        o('b', '5 · Quarterback.'),
        ' At prediction time only: if a team starts a QB other than its recent primary starter (the modal starter over its last eight prior games, once it has at least two), the projected margin drops by ',
        o('code', '4.21'),
        ' points, a penalty fit on 2015–2021 data.',
      ),

      o('h2', 'From rating to margin'),
      o('p',
        'Each PSR above 50 is worth about ',
        o('b', '1.71 points of scoreboard margin'),
        ' on a neutral field; home field adds ',
        o('b', '1.70 points'),
        '. Expected home margin is ',
        o('code', '1.71 × (PSR_home − PSR_away) + 1.70'),
        ', minus the QB penalty where it applies.',
      ),

      o('h2', 'Receipts'),
      o('p',
        'All coefficients were fit on 2015–2021, then the system was backtested walk-forward on 2022–2025 (weeks 5–18) — every prediction uses only games played before it. The Vegas closing line, the strongest public benchmark, is shown for scale.',
      ),
      o('.receipts',
        o('table',
          o('tr',
            o('th'),
            o('th', 'Straight-up winners'),
            o('th', 'Margin MAE'),
            o('th', 'Corr w/ closing spread'),
          ),
          o('tr',
            o('td', 'PSR'),
            o('td', '65.0%'),
            o('td', '9.89'),
            o('td', '0.870'),
          ),
          o('tr',
            o('td', 'Vegas closing line'),
            o('td', '69.0%'),
            o('td', '9.41'),
            o('td', '—'),
          ),
        ),
      ),
      o('p',
        'PSR does not beat the market, and doesn’t claim to. The point is a rating that shows its work: every number on the front page is reproducible from the open pipeline and public nflverse data.',
      ),
    ),
}

const vfFooter = () => [
  'Data from ',
  o('a[href=https://github.com/nflverse]', 'nflverse'),
  ' · pipeline source in the repository’s ',
  o('code', 'pipeline/'),
  ' directory · ratings rebuild automatically each week.',
]
